/*
{
  name: formPlayer.name,
  image: formPlayer.image,
  surname: formPlayer.surname,
  username: formPlayer.username,
  password: formPlayer.password,
  age: formPlayer.age,
  email: formPlayer.email,
  contactNumber: formPlayer.contactNumber,
  country: formPlayer.country,
  province: formPlayer.province,
  clubName: formPlayer.clubName,
  indoor: formPlayer.indoor,
  beach: formPlayer.beach,
  detailClub: formPlayer.detailClub,
  winner: formPlayer.winner,
  loser: formPlayer.loser,
  rate: formPlayer.rate,
  averageRate: formPlayer.averageRate,
  flag: formPlayer.flag,
  nazionality: formPlayer.nazionality,
  dateEvent: formPlayer.dateEvent,
  timeEvent: formPlayer.timeEvent,
  gender: formPlayer.gender,
  level: formPlayer.level,
  locationEvent: formPlayer.locationEvent,
  payment: formPlayer.payment,
  descriptionEvent: formPlayer.descriptionEvent,
  strength: formPlayer.strength,
  flaw: formPlayer.flaw,
  blocker: formPlayer.blocker,
  defense: formPlayer.defense,
  expetaction: formPlayer.expetaction,
  latitude: formPlayer.latitude,
  longitude: formPlayer.longitude,
}

*/
